<template>
  <div>
    <scroll :pull-up-load="true" @pullingUp="load">
      <ul>
        <li>asdf1</li>
        <li>asdf2</li>
        <li>asdf3</li>
        <li>asdf4</li>
        <li>asdf5</li>
        <li>asdf6</li>
        <li>asdf7</li>
        <li>asdf8</li>
        <li>asdf9</li>
        <li>asdf10</li>
        <li>asdf11</li>
        <li>asdf12</li>
        <li>asdf13</li>
        <li>asdf14</li>
        <li>asdf15</li>
        <li>asdf16</li>
        <li>asdf17</li>
        <li>asdf18</li>
        <li>asdf19</li>
        <li>asdf20</li>
        <li>asdf21</li>
        <li>asdf22</li>
        <li>asdf23</li>
        <li>asdf24</li>
        <li>asdf25</li>
        <li>asdf26</li>
        <li>asdf27</li>
        <li>asdf28</li>
        <li>asdf29</li>
        <li>asdf30</li>
        <li>asdf31</li>
        <li>asdf32</li>
        <li>asdf33</li>
        <li>asdf34</li>
        <li>asdf35</li>
        <li>asdf36</li>
        <li>asdf37</li>
        <li>asdf38</li>
        <li>asdf39</li>
        <li>asdf40</li>
        <li>asdf41</li>
        <li>asdf42</li>
        <li>asdf43</li>
        <li>asdf44</li>
        <li>asdf45</li>
        <li>asdf46</li>
        <li>asdf47</li>
        <li>asdf48</li>
        <li>asdf49</li>
        <li>asdf50</li>
        <li>asdf51</li>
        <li>asdf52</li>
        <li>asdf53</li>
        <li>asdf54</li>
        <li>asdf55</li>
        <li>asdf56</li>
        <li>asdf57</li>
        <li>asdf58</li>
        <li>asdf59</li>
        <li>asdf60</li>
        <li>asdf61</li>
        <li>asdf62</li>
        <li>asdf63</li>
        <li>asdf64</li>
        <li>asdf65</li>
        <li>asdf66</li>
        <li>asdf67</li>
        <li>asdf68</li>
        <li>asdf69</li>
        <li>asdf70</li>
        <li>asdf71</li>
        <li>asdf72</li>
        <li>asdf73</li>
        <li>asdf74</li>
        <li>asdf75</li>
        <li>asdf76</li>
        <li>asdf77</li>
        <li>asdf78</li>
        <li>asdf79</li>
        <li>asdf80</li>
        <li>asdf81</li>
        <li>asdf82</li>
        <li>asdf83</li>
        <li>asdf84</li>
        <li>asdf85</li>
        <li>asdf86</li>
        <li>asdf87</li>
        <li>asdf88</li>
        <li>asdf89</li>
        <li>asdf90</li>
        <li>asdf91</li>
        <li>asdf92</li>
        <li>asdf93</li>
        <li>asdf94</li>
        <li>asdf95</li>
        <li>asdf96</li>
        <li>asdf97</li>
        <li>asdf98</li>
        <li>asdf99</li>
        <li>asdf100</li>
        <li>asdf101</li>
        <li>asdf102</li>
        <li>asdf103</li>
        <li>asdf104</li>
        <li>asdf105</li>
        <li>asdf106</li>
        <li>asdf107</li>
        <li>asdf108</li>
        <li>asdf109</li>
        <li>asdf110</li>
        <li>asdf111</li>
        <li>asdf112</li>
        <li>asdf113</li>
        <li>asdf114</li>
        <li>asdf115</li>
        <li>asdf116</li>
        <li>asdf117</li>
        <li>asdf118</li>
        <li>asdf119</li>
        <li>asdf120</li>
        <li>asdf121</li>
        <li>asdf122</li>
        <li>asdf123</li>
        <li>asdf124</li>
        <li>asdf125</li>
        <li>asdf126</li>
        <li>asdf127</li>
        <li>asdf128</li>
        <li>asdf129</li>
        <li>asdf130</li>
        <li>asdf131</li>
        <li>asdf132</li>
        <li>asdf133</li>
        <li>asdf134</li>
        <li>asdf135</li>
        <li>asdf136</li>
        <li>asdf137</li>
        <li>asdf138</li>
        <li>asdf139</li>
        <li>asdf140</li>
        <li>asdf141</li>
        <li>asdf142</li>
        <li>asdf143</li>
        <li>asdf144</li>
        <li>asdf145</li>
        <li>asdf146</li>
        <li>asdf147</li>
        <li>asdf148</li>
        <li>asdf149</li>
        <li>asdf150</li>
        <li>asdf151</li>
        <li>asdf152</li>
        <li>asdf153</li>
        <li>asdf154</li>
        <li>asdf155</li>
        <li>asdf156</li>
        <li>asdf157</li>
        <li>asdf158</li>
        <li>asdf159</li>
        <li>asdf160</li>
        <li>asdf161</li>
        <li>asdf162</li>
        <li>asdf163</li>
        <li>asdf164</li>
        <li>asdf165</li>
        <li>asdf166</li>
        <li>asdf167</li>
        <li>asdf168</li>
        <li>asdf169</li>
        <li>asdf170</li>
        <li>asdf171</li>
        <li>asdf172</li>
        <li>asdf173</li>
        <li>asdf174</li>
        <li>asdf175</li>
        <li>asdf176</li>
        <li>asdf177</li>
        <li>asdf178</li>
        <li>asdf179</li>
        <li>asdf180</li>
        <li>asdf181</li>
        <li>asdf182</li>
        <li>asdf183</li>
        <li>asdf184</li>
        <li>asdf185</li>
        <li>asdf186</li>
        <li>asdf187</li>
        <li>asdf188</li>
        <li>asdf189</li>
        <li>asdf190</li>
        <li>asdf191</li>
        <li>asdf192</li>
        <li>asdf193</li>
        <li>asdf194</li>
        <li>asdf195</li>
        <li>asdf196</li>
        <li>asdf197</li>
        <li>asdf198</li>
        <li>asdf199</li>
        <li>asdf200</li>
      </ul>
    </scroll>
  </div>
</template>

<script>
import Scroll from "../../components/common/scroll/Scroll";
export default {
  name: "Category",
  components: {Scroll},
  methods: {
    load() {
      console.log("啥也没做");
    }
  }
}
</script>

<style scoped>

</style>
